name: "TeddyCloud"
description: "TeddyCloud Instance for Home Assistant"
url: https://github.com/LukasQ/teddycloud_ha_addon
version: "0.3.4"
slug: "teddycloud_ha"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config
  - ssl
webui: https://[HOST]:[PORT:443]
#discovery: mqtt # to be checked
#panel_icon: 
#panel_title: 
stage: experimental
# options:
#   defaults:
#     - 8.8.8.8
#     - 8.8.4.4
#   forwards: []
#   hosts: []
#   services: []
#   cnames: []
#   log_queries: false
# ports:
#   53/tcp: 53
#   53/udp: 53
# schema:
#   defaults:
#     - str
#   forwards:
#     - domain: str
#       server: str
#   hosts:
#     - host: str
#       ip: str
#   services:
#     - host: str
#       port: str
#       priority: int
#       srv: str
#       weight: int
#   cnames:
#     - name: str
#       target: str
#   log_queries: bool
